# Generated by Django 5.1.2 on 2025-03-06 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_new_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='new_slug',
            new_name='news_slug',
        ),
    ]
