# Generated by Django 5.1.2 on 2025-03-06 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Subscribers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='subscriber_email',
            new_name='subscribers_email',
        ),
        migrations.RenameField(
            model_name='subscriber',
            old_name='subscriber_name',
            new_name='subscribers_name',
        ),
    ]
