# Generated by Django 5.1.2 on 2025-03-08 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_image', models.FileField(default=None, max_length=250, null=True, upload_to='members/')),
                ('member_name', models.CharField(max_length=50)),
                ('member_linkdin', models.CharField(max_length=100)),
                ('member_git', models.CharField(max_length=100)),
            ],
        ),
    ]
