# Generated by Django 5.1.2 on 2025-03-08 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='member_linkdin',
            new_name='member_linkedin',
        ),
    ]
